// ----------------------------------------------------------------------------
// Copyright....: (c) SAP 1999-2021
// Project......: 
// Library......: 
// File.........: IKxJModel.java
// Author.......: 
// Created......: Wed Jan 08 15:28:22 2003
// Description..:
// ----------------------------------------------------------------------------

package KxJRT;

/**
 * The Automatic Analytics Java model interface. 
 * Generated Java code for K2R and K2S implements this interface.
 * @version 1.0
 */
public interface IKxJModel {
	
	/**
	 * Specifies the input variables the model needs.
	 * @return array of input variable names.
	 */   
	public String[] getModelInputVariables();

	/**
	 * Specifies the input storage variables the model needs.
	 * @return array of input variable storages.
	 */   
	public String[] getModelInputStorageVariables();

	/**
	 * Specifies the output storage variables the model needs.
	 * @return array of output variable storages.
	 */   
	public String[] getModelOutputStorageVariables();

	/**
	 * Specifies the output variables generated by the model.
	 * @return array of output variable names. 
	 */
	public String[] getModelOutputVariables();
	
	/**
	 * Apply this model on a data row.
	 * @param iInput object providing input variables value.
	 * @return array of results value. Returned objects can be cast to 
	 * Integer (cluster id for K2S) or Float (score and optionally proba
	 * for K2R).
	 */
	public Object[] apply( IKxJModelInput iInput );
} 
