-- @configSQL
DO BEGIN
	 IF NOT EXISTS(SELECT * FROM "SYS"."EFFECTIVE_PRIVILEGES" WHERE "USER_NAME"=CURRENT_USER AND "PRIVILEGE"='USER ADMIN') THEN
	    SIGNAL SQL_ERROR_CODE 10001 SET MESSAGE_TEXT = 'User ' || CURRENT_USER || ' does not have USER ADMIN privilege'; 
	 END IF;
END;
DO BEGIN
	 IF EXISTS(SELECT * FROM USERS WHERE USER_NAME='CHECK_APL') THEN
	 	EXECUTE IMMEDIATE 'DROP USER CHECK_APL CASCADE';
	 END IF;
END;

CREATE USER CHECK_APL PASSWORD &CHECK_APL_PASSWORD;

DO BEGIN
	 IF EXISTS(SELECT * FROM "SYS"."EFFECTIVE_PRIVILEGES" WHERE "USER_NAME"=CURRENT_USER AND "PRIVILEGE"='USER ADMIN') THEN
        IF EXISTS(SELECT * FROM USERS WHERE USER_NAME='CHECK_APL') THEN
	 	    EXECUTE IMMEDIATE 'DROP USER CHECK_APL CASCADE';
	    ELSE
	        SIGNAL SQL_ERROR_CODE 10002 SET MESSAGE_TEXT = 'Probably, the password &CHECK_APL_PASSWORD does not match current HANA Password policy'; 
	    END IF;
    END IF;
 END;

